//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietToaThuoc
    {
        public int MaThuoc { get; set; }
        public int MaToa { get; set; }
        public int SoLuong { get; set; }
        public string LieuDung { get; set; }
    
        public virtual Thuoc Thuoc { get; set; }
        public virtual ToaThuoc ToaThuoc { get; set; }
    }
}
