//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichKham
    {
        public int MaLK { get; set; }
        public int MaBN { get; set; }
        public int MaYT { get; set; }
        public int MaBS { get; set; }
        public System.DateTime NgayHen { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual YTa YTa { get; set; }
    }
}
