//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuKham()
        {
            this.XetNghiem_PhieuKham = new HashSet<XetNghiem_PhieuKham>();
        }
    
        public int MaPK { get; set; }
        public int MaBS { get; set; }
        public int MaBN { get; set; }
        public System.DateTime NgayKham { get; set; }
        public string TrieuChung { get; set; }
        public string ChuanDoan { get; set; }
        public Nullable<System.DateTime> NgayTaiKham { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XetNghiem_PhieuKham> XetNghiem_PhieuKham { get; set; }
    }
}
