//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int MaTK { get; set; }
        public Nullable<int> MaND { get; set; }
        public string TenND { get; set; }
        public string MoTa { get; set; }
        public int MaLNV { get; set; }
    
        public virtual LoaiNhanVien LoaiNhanVien { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
