//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToaThuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToaThuoc()
        {
            this.ChiTietToaThuocs = new HashSet<ChiTietToaThuoc>();
        }
    
        public int MaToa { get; set; }
        public System.DateTime NgayKeToa { get; set; }
        public int MaBS { get; set; }
        public int MaBN { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietToaThuoc> ChiTietToaThuocs { get; set; }
    }
}
