//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class XetNghiem_PhieuKham
    {
        public int MaXN { get; set; }
        public int MaPK { get; set; }
        public System.DateTime NgayXN { get; set; }
        public System.DateTime NgayHenLayKQ { get; set; }
        public string YeuCauXN { get; set; }
        public string KetQuaXN { get; set; }
    
        public virtual PhieuKham PhieuKham { get; set; }
        public virtual XetNghiem XetNghiem { get; set; }
    }
}
