//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class XetNghiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XetNghiem()
        {
            this.XetNghiem_PhieuKham = new HashSet<XetNghiem_PhieuKham>();
        }
    
        public int MaXN { get; set; }
        public string TenXN { get; set; }
        public int MaLXN { get; set; }
        public string MoTa { get; set; }
    
        public virtual LoaiXetNghiem LoaiXetNghiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XetNghiem_PhieuKham> XetNghiem_PhieuKham { get; set; }
    }
}
